//! Golden-fixture integrity tests.
//!
//! Reads `fixtures/manifest.json` (generated by `fixtures/rig/capture.py
//! export`) and checks every committed packet fixture against it: file
//! length, SHA-256 of the payload, and the two-byte big-endian packet
//! header (type | reliable bit). This is intentionally not a codec —
//! the full decoder lands with M2. The manifest format contract is one
//! packet object per line, so this test parses with plain string scans
//! and needs no JSON dependency.
//!
//! The SHA-256 below is a small test-only implementation so the crate
//! keeps zero dependencies.

use std::fs;
use std::path::PathBuf;

const RELIABLE_BIT: u16 = 0x8000;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("fixtures")
}

/// Extract a `"key": "value"` string field from a single-line JSON object.
fn json_str<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let pat = format!("\"{key}\": \"");
    let start = line.find(&pat)? + pat.len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(&rest[..end])
}

/// Extract a `"key": N` numeric field from a single-line JSON object.
fn json_num(line: &str, key: &str) -> Option<u64> {
    let pat = format!("\"{key}\": ");
    let start = line.find(&pat)? + pat.len();
    let rest = &line[start..];
    let end = rest.find([',', '}', ' '])?;
    rest[..end].parse().ok()
}

/// Extract a `"key": true|false` boolean field.
fn json_bool(line: &str, key: &str) -> Option<bool> {
    let pat = format!("\"{key}\": ");
    let start = line.find(&pat)? + pat.len();
    match line[start..].chars().next()? {
        't' => Some(true),
        'f' => Some(false),
        _ => None,
    }
}

struct PacketEntry {
    file: String,
    length: u64,
    sha256: String,
    ptype: u64,
    reliable: bool,
}

fn manifest_entries(manifest: &str) -> Vec<PacketEntry> {
    let mut entries = Vec::new();
    for line in manifest.lines() {
        let line = line.trim();
        if !line.starts_with("{\"i\":") {
            continue;
        }
        let entry = PacketEntry {
            file: json_str(line, "file").expect("packet file").to_string(),
            length: json_num(line, "length").expect("packet length"),
            sha256: json_str(line, "sha256").expect("packet sha256").to_string(),
            ptype: json_num(line, "type").expect("packet type"),
            reliable: json_bool(line, "reliable").expect("packet reliable"),
        };
        entries.push(entry);
    }
    entries
}

#[test]
fn fixtures_match_manifest() {
    let dir = fixtures_dir();
    let manifest_path = dir.join("manifest.json");
    let manifest = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest_path.display()));
    let entries = manifest_entries(&manifest);
    assert!(
        entries.len() >= 50,
        "expected at least 50 fixture packets, found {}",
        entries.len()
    );

    for e in &entries {
        let path = dir.join(&e.file);
        let payload =
            fs::read(&path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));

        assert_eq!(
            payload.len() as u64,
            e.length,
            "length mismatch for {}",
            e.file
        );
        assert_eq!(
            sha256_hex(&payload),
            e.sha256,
            "sha256 mismatch for {}",
            e.file
        );

        // Two-byte big-endian header: type with the reliable bit ORed in.
        assert!(
            payload.len() >= 2,
            "packet too short for a header: {}",
            e.file
        );
        let header = u16::from_be_bytes([payload[0], payload[1]]);
        let want = (e.ptype as u16) | if e.reliable { RELIABLE_BIT } else { 0 };
        assert_eq!(
            header, want,
            "header mismatch for {}: got 0x{header:04x}, want 0x{want:04x}",
            e.file
        );
    }
}

#[test]
fn no_orphan_fixtures() {
    // Every committed .bin under a session directory must be listed in
    // the manifest; the manifest is the single source of truth.
    let dir = fixtures_dir();
    let manifest = fs::read_to_string(dir.join("manifest.json")).expect("read manifest");
    let listed: Vec<&str> = manifest
        .lines()
        .filter(|l| l.trim_start().starts_with("{\"i\":"))
        .filter_map(|l| json_str(l, "file"))
        .collect();

    let mut on_disk = Vec::new();
    for session in fs::read_dir(&dir).expect("read fixtures dir") {
        let session = session.expect("session entry").path();
        if !session.is_dir() || session.file_name().unwrap() == "rig" {
            continue;
        }
        for f in fs::read_dir(&session).expect("read session dir") {
            let f = f.expect("fixture entry").path();
            if f.extension().is_some_and(|x| x == "bin") {
                on_disk.push(format!(
                    "{}/{}",
                    session.file_name().unwrap().to_string_lossy(),
                    f.file_name().unwrap().to_string_lossy()
                ));
            }
        }
    }
    on_disk.sort();

    let mut listed_owned: Vec<String> = listed.into_iter().map(str::to_string).collect();
    listed_owned.sort();
    assert_eq!(
        listed_owned, on_disk,
        "manifest listing and on-disk fixtures diverge"
    );
}

// --- test-only SHA-256 (FIPS 180-4), zero-dependency ---

const K: [u32; 64] = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

const H0: [u32; 8] = [
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
];

fn sha256_hex(data: &[u8]) -> String {
    let mut h = H0;
    let bitlen = (data.len() as u64) * 8;
    let mut msg = data.to_vec();
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bitlen.to_be_bytes());

    for block in msg.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (i, word) in block.chunks_exact(4).enumerate() {
            w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }

    h.iter().map(|x| format!("{x:08x}")).collect()
}

#[test]
fn sha256_known_answers() {
    assert_eq!(
        sha256_hex(b""),
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );
    assert_eq!(
        sha256_hex(b"abc"),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
    assert_eq!(
        sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
        "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
    );
}
